### ISSUE TITLE
How to start this program?

### ISSUE THREAD

**Issue by lemorage** [yli262/tour-into-the-picture#19]
I checked out `package.json`, and installed all the dependencies on my local. But when I used `yarn start` to start the program, I got notified `No entries found.`. I don't know what was going on.
```
 tour-into-the-picture-master yarn start
$ parcel ./src/index.html
Server running at http://localhost:1234
🚨  No entries found.
    at Bundler.bundle (/Users/clannad/Documents/tour-into-the-picture-master/node_modules/parcel-bundler/src/Bundler.js:275:17)
    at async Bundler.serve (/Users/clannad/Documents/tour-into-the-picture-master/node_modules/parcel-bundler/src/Bundler.js:842:7)
    at async Command.bundle (/Users/clannad/Documents/tour-into-the-picture-master/node_modules/parcel-bundler/src/cli.js:241:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by zhanglinchao1314** [comment]
"start": "parcel ./index.html",
